# Page settings

baseURL = "https://jrbeverly.me/"
languageCode = "en"
title = "Udacity - jrbeverly"
theme = "hugo-devresume-theme"

[params]
    author = "Jonathan Beverly (jrbeverly)"
    description = "Udacity Certificates and Projects"

    primaryColor = "#02B3E4"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Udacity"
        tagline = "jrbeverly certificates"
        avatar = "profile.png"

       [params.skills]
        enable = true

        [[params.skills.items]]
        details = "Jupyter Notebook"
        [[params.skills.items]]
        details = "Python"
        [[params.skills.items]]
        details = "matplotlib"
        [[params.skills.items]]
        details = "pandas"
        [[params.skills.items]]
        details = "numpy"
        [[params.skills.items]]
        details = "sklearn"
        [[params.skills.items]]
        details = "JavaScript"
        [[params.skills.items]]
        details = "react"
        [[params.skills.items]]
        details = "react-native"
        [[params.skills.items]]
        details = "redux"

    [params.summary]
        enable = true
        text = "This page acts as a statement of record for my Udacity Nanodegree Projects. I was given the opportunity to learn through Udacity, a technology educational organization, through previous places of employ. The profile for my user jrbeverly is no longer accessible at Udacity, as I no longer make use of the platform."

    [params.experience]
        enable = true

        [[params.experience.entry]]
        title = "Machine Learning Nanodegree"

        [[params.experience.entry.list]]
        title = "Predicting Boston Housing Prices"
        dates = "Fall 2018"
        company = "Udacity"
        details = "Leverage a few basic machine learning concepts to assist you and a client with finding the best selling price for their home."
        url = "https://github.com/jrbeverly/boston-housing"
        github = "https://github.com/jrbeverly/boston-housing"
        gitlab = "https://gitlab.com/jrbeverly/boston-housing"

        [[params.experience.entry.list]]
        title = "Creating Customer Segments"
        dates = "Fall 2018"
        company = "Udacity"
        details = "Applying unsupervised learning techniques on product spending data to identify customer segments hidden in the data."
        url = "https://github.com/jrbeverly/customer-segments"
        github = "https://github.com/jrbeverly/customer-segments"
        gitlab = "https://gitlab.com/jrbeverly/customer-segments"

        [[params.experience.entry.list]]
        title = "Finding Donors for CharityML"
        dates = "Fall 2018"
        company = "Udacity"
        details = "CharityML is a fictitious charity organization that was established to provide financial support for people eager to learn machine learning."
        url = "https://github.com/jrbeverly/charityml"
        github = "https://github.com/jrbeverly/charityml"
        gitlab = "https://gitlab.com/jrbeverly/charityml"

        [[params.experience.entry.list]]
        title = "Classification of Dogs"
        dates = "Fall 2018"
        company = "Udacity"
        details = "Implementation of the Convolutional Neural Networks (CNN) algorithm for identifying a canineâ€™s breed from an image. Additionally, supply the resembled dog breed if provided an image of a human."
        url = "https://github.com/jrbeverly/dog-project"
        github = "https://github.com/jrbeverly/dog-project"
        gitlab = "https://gitlab.com/jrbeverly/dog-project"

        [[params.experience.entry.list]]
        title = "Quadcopter using Reinforcement Learning"
        dates = "Fall 2018"
        company = "Udacity"
        details = "A quadcopter flying agent that learns to take off using reinforcement learning."
        url = "https://github.com/jrbeverly/quadcopter"
        github = "https://github.com/jrbeverly/quadcopter"
        gitlab = "https://gitlab.com/jrbeverly/quadcopter"

        [[params.experience.entry]]
        title = "React Nanodegree"

        [[params.experience.entry.list]]
        title = "MyReads"
        dates = "Winter 2017"
        company = "Udacity"
        details = "A digital bookshelf app that allows you to select and categorize books you have read, are currently reading, or want to read."
        url = "https://github.com/jrbeverly/myreads"
        github = "https://github.com/jrbeverly/myreads"
        gitlab = "https://gitlab.com/jrbeverly/myreads"

        [[params.experience.entry.list]]
        title = "Classification of Dogs"
        dates = "Winter 2017"
        company = "Udacity"
        details = "A content and comment web app. Users are able to post content to predefined categories, comment on their posts and other users' posts, and vote on posts and comments. Users are also able to edit and delete posts and comments."
        url = "https://github.com/jrbeverly/Readable"
        github = "https://github.com/jrbeverly/Readable"
        gitlab = "https://gitlab.com/jrbeverly/Readable"

        [[params.experience.entry.list]]
        title = "UdaciCards"
        dates = "Winter 2017"
        company = "Udacity"
        details = "A mobile application that allows users to study collections of flashcards. The app allows users to create different categories of flashcards called decks, add flashcards to those decks, then take quizzes on those decks."
        url = "https://github.com/jrbeverly/UdaciCards"
        github = "https://github.com/jrbeverly/UdaciCards"
        gitlab = "https://gitlab.com/jrbeverly/UdaciCards"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/jrbeverly"
        title = "jrbeverly"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://ca.linkedin.com/in/jrbeverly/"
        title = "jrbeverly"

